org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Use Flutter built-in Kotlin support (required with AGP 9.0.1+)
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
